### ISSUE TITLE
Colours of lines in dark mode

### ISSUE THREAD

**Issue by biohazd** [WeatherXM/wxm-ios#1]
Can you make the line colours in dark mode easier to see a difference. They are very similar in color so it’s not easy to tell them apart at a glance.
![Uploading IMG_2094.jpeg…]()

### **Describe alternatives you've considered**

A clear and concise description of any alternative solutions you've considered.

**Comment by JohnFrontzos** [comment]
Hi @biohazd and thank you for your feedback 🙏 . I will forward your suggestion to our UX team.
