### ISSUE TITLE
Reward Timeline View Discrepancy

### ISSUE THREAD

**Issue by mickied** [WeatherXM/wxm-ios#73]
## **Describe the bug**

On the reward timeline view, the boost rewards shown on the daily reward panel do not match the boost rewards shown when tapping on the panel to view additional details.  Because of this, the total rewards do not match either.

It appears that the boost rewards shown on the details page are the rewards from the following day.

### **How To Reproduce**

1. Go to an owned station in the app.
2. Tap on "rewards".
3. Scroll down to "Weakly Streak" and tap on "View Timeline".
4. Choose a day where the boost rewards from one day do not match the boost rewards from the previous day.
5. Take note of the total earnings from that day as well as the boost rewards then tap on that day.
6. Notice that the total rewards and the boost rewards do not match what the panel said.

### **Expected behavior**

The total rewards and the boost rewards displayed on the timeline panels should match the rewards shown when tapping on that panel.

### **Screenshots**

Notice the daily reward for April 26th is 5.127 $WXM and the boost reward is 1.8693 $WXM.
![image](https://github.com/WeatherXM/wxm-ios/assets/13276585/16ed3254-2102-4284-803b-15b12b4641b6)
  
Notice the daily reward and boost reward for April 26th do not match. It does match the daily reward and boost reward for April 27th however.
![image](https://github.com/WeatherXM/wxm-ios/assets/13276585/60254058-b986-474f-86dd-1ff21dca3901)

### **If Applicable: Smartphone (please complete the following information that are needed for this bug):**

- Device: iPhone 12 Pro Max
- iOS Version: 17.4.1
- iOS App Version: 1.15.0

**Comment by JohnFrontzos** [comment]
Thank you for your feedback @mickied. Could you please tell me your station's name?

**Comment by mickied** [comment]
No, at least not publicly, and not without a good understanding of why you'd need it.  This bug report is not unique to my station.  It happens on other stations I'm following as well, regardless of whether they are WiFi or Helium.

**Comment by JohnFrontzos** [comment]
I tried to reproduce it to my stations stations but I couldn't, so it seems that it's not an application bug. That's why we need to verify your station's data and investigate the full flow. You can submit a contact request in our [support portal](https://support.weatherxm.com/) with your station's information and with a reference in this GitHub, and we will investigate further.

**Comment by mickied** [comment]
Ok, I've done that.

**Comment by mickied** [comment]
Here's an example of a station I'm following that it happens with.
![image](https://github.com/WeatherXM/wxm-ios/assets/13276585/265147f0-fa47-44d3-aa99-5d9cff35ae81)
  
![image](https://github.com/WeatherXM/wxm-ios/assets/13276585/22b9d1d7-853d-4de8-b1a7-35b4db972a1c)

**Comment by JohnFrontzos** [comment]
Thank you for the extra information. We are investigating the issue and I'll send you back when we have any updates.
